// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x5B5EE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu1 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Menu1, 480);
    lv_obj_set_height(ui_Menu1, 30);
    lv_obj_set_x(ui_Menu1, 0);
    lv_obj_set_y(ui_Menu1, -111);
    lv_obj_set_align(ui_Menu1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Menu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Step1 = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Step1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Step1, -132);
    lv_obj_set_y(ui_Step1, 0);
    lv_obj_set_align(ui_Step1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Step1, "Step1_X");

    ui_Step2 = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Step2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Step2, -58);
    lv_obj_set_y(ui_Step2, 0);
    lv_obj_set_align(ui_Step2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Step2, "Step2_Y");

    ui_Step3 = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Step3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Step3, 23);
    lv_obj_set_y(ui_Step3, 0);
    lv_obj_set_align(ui_Step3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Step3, "Step3_Z");

    ui_Step4 = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Step4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Step4, 98);
    lv_obj_set_y(ui_Step4, 0);
    lv_obj_set_align(ui_Step4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Step4, "Step4");

    ui_Step5 = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Step5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Step5, 178);
    lv_obj_set_y(ui_Step5, 0);
    lv_obj_set_align(ui_Step5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Step5, "Step5");

    ui_Division = lv_label_create(ui_Menu1);
    lv_obj_set_width(ui_Division, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Division, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Division, -202);
    lv_obj_set_y(ui_Division, 0);
    lv_obj_set_align(ui_Division, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Division, "Division");

    ui_Menu2 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Menu2, 65);
    lv_obj_set_height(ui_Menu2, 253);
    lv_obj_set_x(ui_Menu2, -206);
    lv_obj_set_y(ui_Menu2, 31);
    lv_obj_set_align(ui_Menu2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Menu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EN = lv_label_create(ui_Menu2);
    lv_obj_set_width(ui_EN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EN, 0);
    lv_obj_set_y(ui_EN, -79);
    lv_obj_set_align(ui_EN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EN, "EN");

    ui_DIR = lv_label_create(ui_Menu2);
    lv_obj_set_width(ui_DIR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIR, 0);
    lv_obj_set_y(ui_DIR, -29);
    lv_obj_set_align(ui_DIR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DIR, "DIR");

    ui_SPEED = lv_label_create(ui_Menu2);
    lv_obj_set_width(ui_SPEED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPEED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPEED, 0);
    lv_obj_set_y(ui_SPEED, 33);
    lv_obj_set_align(ui_SPEED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPEED, "SPEED");

    ui_STEP = lv_label_create(ui_Menu2);
    lv_obj_set_width(ui_STEP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEP, 0);
    lv_obj_set_y(ui_STEP, 87);
    lv_obj_set_align(ui_STEP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STEP, "STEP");

    ui_Switch1 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -131);
    lv_obj_set_y(ui_Switch1, -50);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Switch2 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -56);
    lv_obj_set_y(ui_Switch2, -50);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Switch3 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 20);
    lv_obj_set_y(ui_Switch3, -50);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Switch4 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 103);
    lv_obj_set_y(ui_Switch4, -50);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_Switch5 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 178);
    lv_obj_set_y(ui_Switch5, -50);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);


    ui_Switch6 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, -131);
    lv_obj_set_y(ui_Switch6, 0);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);


    ui_Switch7 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, -56);
    lv_obj_set_y(ui_Switch7, 0);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);


    ui_Switch8 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 20);
    lv_obj_set_y(ui_Switch8, 0);
    lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);


    ui_Switch9 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch9, 50);
    lv_obj_set_height(ui_Switch9, 25);
    lv_obj_set_x(ui_Switch9, 103);
    lv_obj_set_y(ui_Switch9, 0);
    lv_obj_set_align(ui_Switch9, LV_ALIGN_CENTER);


    ui_Switch10 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch10, 50);
    lv_obj_set_height(ui_Switch10, 25);
    lv_obj_set_x(ui_Switch10, 178);
    lv_obj_set_y(ui_Switch10, 0);
    lv_obj_set_align(ui_Switch10, LV_ALIGN_CENTER);


    ui_Label11 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -145);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "STEP MOTOR Function TEST");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFE9500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button1, 60);
    lv_obj_set_height(ui_Button1, 30);
    lv_obj_set_x(ui_Button1, -134);
    lv_obj_set_y(ui_Button1, 115);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button2, 60);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_x(ui_Button2, -58);
    lv_obj_set_y(ui_Button2, 115);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 30);
    lv_obj_set_x(ui_Button3, 21);
    lv_obj_set_y(ui_Button3, 115);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button4, 60);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 108);
    lv_obj_set_y(ui_Button4, 115);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button5, 60);
    lv_obj_set_height(ui_Button5, 30);
    lv_obj_set_x(ui_Button5, 185);
    lv_obj_set_y(ui_Button5, 115);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_Dropdown1, "100\n200\n300");
    lv_obj_set_width(ui_Dropdown1, 60);
    lv_obj_set_height(ui_Dropdown1, 30);
    lv_obj_set_x(ui_Dropdown1, -132);
    lv_obj_set_y(ui_Dropdown1, 60);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Dropdown2 = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_Dropdown2, "100\n200\n300");
    lv_obj_set_width(ui_Dropdown2, 60);
    lv_obj_set_height(ui_Dropdown2, 30);
    lv_obj_set_x(ui_Dropdown2, -58);
    lv_obj_set_y(ui_Dropdown2, 60);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Dropdown3 = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_Dropdown3, "100\n200\n300");
    lv_obj_set_width(ui_Dropdown3, 60);
    lv_obj_set_height(ui_Dropdown3, 30);
    lv_obj_set_x(ui_Dropdown3, 22);
    lv_obj_set_y(ui_Dropdown3, 60);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Dropdown4 = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_Dropdown4, "100\n200\n300");
    lv_obj_set_width(ui_Dropdown4, 60);
    lv_obj_set_height(ui_Dropdown4, 30);
    lv_obj_set_x(ui_Dropdown4, 107);
    lv_obj_set_y(ui_Dropdown4, 60);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Dropdown5 = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_Dropdown5, "100\n200\n300");
    lv_obj_set_width(ui_Dropdown5, 60);
    lv_obj_set_height(ui_Dropdown5, 30);
    lv_obj_set_x(ui_Dropdown5, 185);
    lv_obj_set_y(ui_Dropdown5, 60);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label12 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -136);
    lv_obj_set_y(ui_Label12, 115);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "512");

    ui_Label13 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -60);
    lv_obj_set_y(ui_Label13, 115);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "512");

    ui_Label14 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 18);
    lv_obj_set_y(ui_Label14, 115);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "512");

    ui_Label15 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 106);
    lv_obj_set_y(ui_Label15, 115);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "512");

    ui_Label16 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 185);
    lv_obj_set_y(ui_Label16, 115);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "512");

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch8, ui_event_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch9, ui_event_Switch9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch10, ui_event_Switch10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown4, ui_event_Dropdown4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown5, ui_event_Dropdown5, LV_EVENT_ALL, NULL);

}
