// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x5B5EE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -132);
    lv_obj_set_y(ui_Label1, -115);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Step1_X");

    ui_Label2 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -58);
    lv_obj_set_y(ui_Label2, -115);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Step2_Y");

    ui_Label3 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 18);
    lv_obj_set_y(ui_Label3, -115);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Step3_Z");

    ui_Label4 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 98);
    lv_obj_set_y(ui_Label4, -115);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Step4");

    ui_Label5 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 178);
    lv_obj_set_y(ui_Label5, -116);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Step5");

    ui_Switch1 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -131);
    lv_obj_set_y(ui_Switch1, -50);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Switch2 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -56);
    lv_obj_set_y(ui_Switch2, -50);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Switch3 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 20);
    lv_obj_set_y(ui_Switch3, -50);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Switch4 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 103);
    lv_obj_set_y(ui_Switch4, -50);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_Switch5 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 178);
    lv_obj_set_y(ui_Switch5, -50);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);


    ui_Spinbox1 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox1, 70);
    lv_obj_set_height(ui_Spinbox1, 42);
    lv_obj_set_x(ui_Spinbox1, -135);
    lv_obj_set_y(ui_Spinbox1, 60);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 0);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox1, round(pow(10, 1 - 1)));

    ui_Spinbox2 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox2, 70);
    lv_obj_set_height(ui_Spinbox2, 42);
    lv_obj_set_x(ui_Spinbox2, -55);
    lv_obj_set_y(ui_Spinbox2, 60);
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox2, 4, 0);
    lv_spinbox_set_range(ui_Spinbox2, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox2, round(pow(10, 1 - 1)));

    ui_Spinbox3 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox3, 70);
    lv_obj_set_height(ui_Spinbox3, 42);
    lv_obj_set_x(ui_Spinbox3, 25);
    lv_obj_set_y(ui_Spinbox3, 60);
    lv_obj_set_align(ui_Spinbox3, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox3, 4, 0);
    lv_spinbox_set_range(ui_Spinbox3, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox3, round(pow(10, 1 - 1)));

    ui_Spinbox4 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox4, 70);
    lv_obj_set_height(ui_Spinbox4, 42);
    lv_obj_set_x(ui_Spinbox4, 104);
    lv_obj_set_y(ui_Spinbox4, 60);
    lv_obj_set_align(ui_Spinbox4, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox4, 4, 0);
    lv_spinbox_set_range(ui_Spinbox4, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox4, round(pow(10, 1 - 1)));

    ui_Spinbox5 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox5, 70);
    lv_obj_set_height(ui_Spinbox5, 42);
    lv_obj_set_x(ui_Spinbox5, 187);
    lv_obj_set_y(ui_Spinbox5, 60);
    lv_obj_set_align(ui_Spinbox5, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox5, 4, 0);
    lv_spinbox_set_range(ui_Spinbox5, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox5, round(pow(10, 1 - 1)));

    ui_Label6 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -212);
    lv_obj_set_y(ui_Label6, -114);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "dev");

    ui_Label7 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -209);
    lv_obj_set_y(ui_Label7, -50);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "EN");

    ui_Label8 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -207);
    lv_obj_set_y(ui_Label8, 12);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "DIR");

    ui_Label9 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -206);
    lv_obj_set_y(ui_Label9, 60);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SPEED");

    ui_Label10 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -211);
    lv_obj_set_y(ui_Label10, 116);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "STEP");

    ui_Switch6 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, -131);
    lv_obj_set_y(ui_Switch6, 0);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);


    ui_Switch7 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, -56);
    lv_obj_set_y(ui_Switch7, 0);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);


    ui_Switch8 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 20);
    lv_obj_set_y(ui_Switch8, 0);
    lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);


    ui_Switch9 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch9, 50);
    lv_obj_set_height(ui_Switch9, 25);
    lv_obj_set_x(ui_Switch9, 103);
    lv_obj_set_y(ui_Switch9, 0);
    lv_obj_set_align(ui_Switch9, LV_ALIGN_CENTER);


    ui_Switch10 = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_Switch10, 50);
    lv_obj_set_height(ui_Switch10, 25);
    lv_obj_set_x(ui_Switch10, 178);
    lv_obj_set_y(ui_Switch10, 0);
    lv_obj_set_align(ui_Switch10, LV_ALIGN_CENTER);


    ui_Spinbox7 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox7, 70);
    lv_obj_set_height(ui_Spinbox7, 42);
    lv_obj_set_x(ui_Spinbox7, -135);
    lv_obj_set_y(ui_Spinbox7, 120);
    lv_obj_set_align(ui_Spinbox7, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox7, 4, 0);
    lv_spinbox_set_range(ui_Spinbox7, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox7, round(pow(10, 1 - 1)));

    ui_Spinbox8 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox8, 70);
    lv_obj_set_height(ui_Spinbox8, 42);
    lv_obj_set_x(ui_Spinbox8, -55);
    lv_obj_set_y(ui_Spinbox8, 120);
    lv_obj_set_align(ui_Spinbox8, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox8, 4, 0);
    lv_spinbox_set_range(ui_Spinbox8, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox8, round(pow(10, 1 - 1)));

    ui_Spinbox9 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox9, 70);
    lv_obj_set_height(ui_Spinbox9, 42);
    lv_obj_set_x(ui_Spinbox9, 25);
    lv_obj_set_y(ui_Spinbox9, 120);
    lv_obj_set_align(ui_Spinbox9, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox9, 4, 0);
    lv_spinbox_set_range(ui_Spinbox9, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox9, round(pow(10, 1 - 1)));

    ui_Spinbox10 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox10, 70);
    lv_obj_set_height(ui_Spinbox10, 42);
    lv_obj_set_x(ui_Spinbox10, 104);
    lv_obj_set_y(ui_Spinbox10, 120);
    lv_obj_set_align(ui_Spinbox10, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox10, 4, 0);
    lv_spinbox_set_range(ui_Spinbox10, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox10, round(pow(10, 1 - 1)));

    ui_Spinbox11 = lv_spinbox_create(ui_Main);
    lv_obj_set_width(ui_Spinbox11, 70);
    lv_obj_set_height(ui_Spinbox11, 42);
    lv_obj_set_x(ui_Spinbox11, 187);
    lv_obj_set_y(ui_Spinbox11, 120);
    lv_obj_set_align(ui_Spinbox11, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox11, 4, 0);
    lv_spinbox_set_range(ui_Spinbox11, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox11, round(pow(10, 1 - 1)));

    ui_Label11 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -145);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "STEP MOTOR Function TEST");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFE9500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch8, ui_event_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch9, ui_event_Switch9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch10, ui_event_Switch10, LV_EVENT_ALL, NULL);

}
