// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Spinbox1;
lv_obj_t * ui_Spinbox2;
lv_obj_t * ui_Spinbox3;
lv_obj_t * ui_Spinbox4;
lv_obj_t * ui_Spinbox5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
void ui_event_Switch6(lv_event_t * e);
lv_obj_t * ui_Switch6;
void ui_event_Switch7(lv_event_t * e);
lv_obj_t * ui_Switch7;
void ui_event_Switch8(lv_event_t * e);
lv_obj_t * ui_Switch8;
void ui_event_Switch9(lv_event_t * e);
lv_obj_t * ui_Switch9;
void ui_event_Switch10(lv_event_t * e);
lv_obj_t * ui_Switch10;
lv_obj_t * ui_Spinbox7;
lv_obj_t * ui_Spinbox8;
lv_obj_t * ui_Spinbox9;
lv_obj_t * ui_Spinbox10;
lv_obj_t * ui_Spinbox11;
lv_obj_t * ui_Label11;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step1_X_EN(e);
    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step2_Y_EN(e);
    }
}
void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step3_Z_EN(e);
    }
}
void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step4_EN(e);
    }
}
void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step5_EN(e);
    }
}
void ui_event_Switch6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step1_X_DIR(e);
    }
}
void ui_event_Switch7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step2_Y_DIR(e);
    }
}
void ui_event_Switch8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step3_Z_DIR(e);
    }
}
void ui_event_Switch9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step4_DIR(e);
    }
}
void ui_event_Switch10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Step5_DIR(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
