// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Spinbox2;
extern lv_obj_t * ui_Spinbox3;
extern lv_obj_t * ui_Spinbox4;
extern lv_obj_t * ui_Spinbox5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
void ui_event_Switch7(lv_event_t * e);
extern lv_obj_t * ui_Switch7;
void ui_event_Switch8(lv_event_t * e);
extern lv_obj_t * ui_Switch8;
void ui_event_Switch9(lv_event_t * e);
extern lv_obj_t * ui_Switch9;
void ui_event_Switch10(lv_event_t * e);
extern lv_obj_t * ui_Switch10;
extern lv_obj_t * ui_Spinbox7;
extern lv_obj_t * ui_Spinbox8;
extern lv_obj_t * ui_Spinbox9;
extern lv_obj_t * ui_Spinbox10;
extern lv_obj_t * ui_Spinbox11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
