// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Menu1;
extern lv_obj_t * ui_Step1;
extern lv_obj_t * ui_Step2;
extern lv_obj_t * ui_Step3;
extern lv_obj_t * ui_Step4;
extern lv_obj_t * ui_Step5;
extern lv_obj_t * ui_Division;
extern lv_obj_t * ui_Menu2;
extern lv_obj_t * ui_EN;
extern lv_obj_t * ui_DIR;
extern lv_obj_t * ui_SPEED;
extern lv_obj_t * ui_STEP;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
void ui_event_Switch7(lv_event_t * e);
extern lv_obj_t * ui_Switch7;
void ui_event_Switch8(lv_event_t * e);
extern lv_obj_t * ui_Switch8;
void ui_event_Switch9(lv_event_t * e);
extern lv_obj_t * ui_Switch9;
void ui_event_Switch10(lv_event_t * e);
extern lv_obj_t * ui_Switch10;
extern lv_obj_t * ui_Label11;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
void ui_event_Dropdown5(lv_event_t * e);
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
