// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Step1_X_EN(lv_event_t * e);
void Step2_Y_EN(lv_event_t * e);
void Step3_Z_EN(lv_event_t * e);
void Step4_EN(lv_event_t * e);
void Step5_EN(lv_event_t * e);
void Step1_X_DIR(lv_event_t * e);
void Step2_Y_DIR(lv_event_t * e);
void Step3_Z_DIR(lv_event_t * e);
void Step4_DIR(lv_event_t * e);
void Step5_DIR(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
