// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_wang

#include "ui.h"

int indx = 0;

void button1Clicked(lv_event_t * e)
{
	// Your code here
	indx++;

	if (indx == 1)
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x003a57), LV_PART_MAIN);
	}

	else if (indx == 2)
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x00FF00), LV_PART_MAIN);
	}

	else if (indx == 3)
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0xFF0000), LV_PART_MAIN);
	}

	else if (indx == 4)
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x123456), LV_PART_MAIN);
	}

	else if (indx == 5)
	{
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x0000ff), LV_PART_MAIN);
		indx = 0;
	}
}
