// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void Step1_X_EN(lv_event_t * e)
{
	// Your code here
}

void Step2_Y_EN(lv_event_t * e)
{
	// Your code here
}

void Step3_Z_EN(lv_event_t * e)
{
	// Your code here
}

void Step4_EN(lv_event_t * e)
{
	// Your code here
}

void Step5_EN(lv_event_t * e)
{
	// Your code here
}

void Step1_X_DIR(lv_event_t * e)
{
	// Your code here
}

void Step2_Y_DIR(lv_event_t * e)
{
	// Your code here
}

void Step3_Z_DIR(lv_event_t * e)
{
	// Your code here
}

void Step4_DIR(lv_event_t * e)
{
	// Your code here
}

void Step5_DIR(lv_event_t * e)
{
	// Your code here
}

void Step1_X_Step(lv_event_t * e)
{
	// Your code here
}

void Step2_Y_Step(lv_event_t * e)
{
	// Your code here
}

void Step3_Z_Step(lv_event_t * e)
{
	// Your code here
}

void Step4_Step(lv_event_t * e)
{
	// Your code here
}

void Step5_Step(lv_event_t * e)
{
	// Your code here
}

void Step1_X_Speed(lv_event_t * e)
{
	// Your code here
}

void Step2_Y_Speed(lv_event_t * e)
{
	// Your code here
}

void Step3_Z_Speed(lv_event_t * e)
{
	// Your code here
}

void Step4_Speed(lv_event_t * e)
{
	// Your code here
}

void Step5_Speed(lv_event_t * e)
{
	// Your code here
}
