// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"


void Step1_X_EN(lv_event_t * e)
{
  //gpioPinWrite(stepper->_enablePin,  _DEF_HIGH);
}

void Step1_X_DIR(lv_event_t * e)
{
  //gpioPinWrite(stepper->_dirPin,  _DEF_HIGH);
}

void Step1_X_CMD(lv_event_t * e)
{
	// Your code here
}
