/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 160    V = 113

        Convert to Color RGB565 16bit/pixel      Total : 36160 Bytes
*/

#include "image.h"

const UI_Image Fan0_32x32x4           = { (void *)fan0_32x32x4, 32, 32};
const UI_Image Fan1_32x32x4           = { (void *)fan1_32x32x4, 32, 32};
const UI_Image Fan_Slow0_64x64x4      = { (void *)fan_slow0_64x64x4, 64, 64};
const UI_Image Fan_Slow1_64x64x4      = { (void *)fan_slow1_64x64x4, 64, 64};
const UI_Image Fan_Fast0_64x64x4      = { (void *)fan_fast0_64x64x4, 64, 64};
const UI_Image Fan_Fast1_64x64x4      = { (void *)fan_fast1_64x64x4, 64, 64};

